name: Deploy to Azure

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Log in to Azure
      run: |
        az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
        az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./terraform

    - name: Deploy Receive Log Function to Azure
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.FUNCTION_APP_NAME_RECEIVE_LOG }}
        package: "./ReceiveLogEntry"
        publish-profile: ${{ secrets.PUBLISH_PROFILE_RECEIVE_LOG }}
        respect-pom-xml: false
        respect-funcignore: false
        scm-do-build-during-deployment: false
        enable-oryx-build: false
        remote-build: false

    - name: Deploy Retrieve Log Function to Azure
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.FUNCTION_APP_NAME_RETRIEVE_LOG }}
        package: "./RetrieveLogEntries"
        publish-profile: ${{ secrets.PUBLISH_PROFILE_RETRIEVE_LOG }}
        respect-pom-xml: false
        respect-funcignore: false
        scm-do-build-during-deployment: false
        enable-oryx-build: false
        remote-build: false

    - name: Debug Environment Variables
      run: |
        echo "FUNCTION_APP_NAME_RECEIVE_LOG: ${{ secrets.FUNCTION_APP_NAME_RECEIVE_LOG }}"
        echo "PUBLISH_PROFILE_RECEIVE_LOG: ${{ secrets.PUBLISH_PROFILE_RECEIVE_LOG }}"
        echo "FUNCTION_APP_NAME_RETRIEVE_LOG: ${{ secrets.FUNCTION_APP_NAME_RETRIEVE_LOG }}"
        echo "PUBLISH_PROFILE_RETRIEVE_LOG: ${{ secrets.PUBLISH_PROFILE_RETRIEVE_LOG }}"