name: Deploy to Azure

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install dependencies for Receive Log Function
      run: |
        cd ./ReceiveLogEntry
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        deactivate
        zip -r ../ReceiveLogEntry.zip .
      shell: bash

    - name: Deploy Receive Log Function to Azure
      run: |
        az functionapp deployment source config-zip -g ${{ secrets.RESOURCE_GROUP_NAME }} -n ${{ secrets.FUNCTION_APP_NAME_RECEIVE_LOG }} --src ReceiveLogEntry.zip

    - name: Install dependencies for Retrieve Log Function
      run: |
        cd ./RetrieveLogEntries
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        deactivate
        zip -r ../RetrieveLogEntries.zip .
      shell: bash

    - name: Deploy Retrieve Log Function to Azure
      run: |
        az functionapp deployment source config-zip -g ${{ secrets.RESOURCE_GROUP_NAME }} -n ${{ secrets.FUNCTION_APP_NAME_RETRIEVE_LOG }} --src RetrieveLogEntries.zip

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Log in to Azure
      run: |
        az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
        az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./terraform

    - name: Debug Environment Variables
      run: |
        echo "FUNCTION_APP_NAME_RECEIVE_LOG: ${{ secrets.FUNCTION_APP_NAME_RECEIVE_LOG }}"
        echo "FUNCTION_APP_NAME_RETRIEVE_LOG: ${{ secrets.FUNCTION_APP_NAME_RETRIEVE_LOG }}"