name: Deploy to Azure

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Log in to Azure
      run: |
        az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
        az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./terraform

    - name: Get Publish Profile for Receive Log Function
      id: get-publish-profile-receive
      run: |
        FUNCTION_APP_NAME_RECEIVE_LOG="logservice-fa-receive-log"
        echo "Getting publish profile for function app: $FUNCTION_APP_NAME_RECEIVE_LOG"
        az webapp deployment list-publishing-profiles --name $FUNCTION_APP_NAME_RECEIVE_LOG --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --output json > publishProfileReceiveLog.json
        cat publishProfileReceiveLog.json
        publish_profile=$(jq -r '.[0].publishProfile' publishProfileReceiveLog.json)
        echo "::set-output name=publish_profile_receive::$publish_profile"
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Deploy Receive Log Function to Azure
      uses: Azure/functions-action@v1
      with:
        app-name: "logservice-fa-receive-log"
        package: "./ReceiveLogEntry"
        publish-profile: ${{ steps.get-publish-profile-receive.outputs.publish_profile_receive }}

    - name: Get Publish Profile for Retrieve Log Function
      id: get-publish-profile-retrieve
      run: |
        FUNCTION_APP_NAME_RETRIEVE_LOG="logservice-fa-retrieve-log"
        echo "Getting publish profile for function app: $FUNCTION_APP_NAME_RETRIEVE_LOG"
        az webapp deployment list-publishing-profiles --name $FUNCTION_APP_NAME_RETRIEVE_LOG --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --output json > publishProfileRetrieveLog.json
        cat publishProfileRetrieveLog.json
        publish_profile=$(jq -r '.[0].publishProfile' publishProfileRetrieveLog.json)
        echo "::set-output name=publish_profile_retrieve::$publish_profile"
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Deploy Retrieve Log Function to Azure
      uses: Azure/functions-action@v1
      with:
        app-name: "logservice-fa-retrieve-log"
        package: "./RetrieveLogEntries"
        publish-profile: ${{ steps.get-publish-profile-retrieve.outputs.publish_profile_retrieve }}

    - name: Debug Environment Variables
      run: |
        echo "PUBLISH_PROFILE_RECEIVE_LOG: ${{ steps.get-publish-profile-receive.outputs.publish_profile_receive }}"
        echo "PUBLISH_PROFILE_RETRIEVE_LOG: ${{ steps.get-publish-profile-retrieve.outputs.publish_profile_retrieve }}"