name: Deploy Azure Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./terraform
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./terraform
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Output Function App Name
      id: output
      run: echo "::set-output name=function_app_name::$(terraform output -raw function_app_name)"
      working-directory: ./terraform

    - name: Get Publish Profile
      id: get_publish_profile
      run: |
        az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
        az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}
        az webapp deployment list-publishing-profiles --name ${{ steps.output.outputs.function_app_name }} --resource-group <ResourceGroupName> --output tsv > publishProfile.txt
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Read Publish Profile
      id: read_publish_profile
      run: |
        publish_profile=$(cat publishProfile.txt)
        echo "::set-output name=publish_profile::$publish_profile"

    - name: Deploy to Azure
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ steps.output.outputs.function_app_name }}
        package: "."
        publish-profile: ${{ steps.read_publish_profile.outputs.publish_profile }}