name: Deploy to Azure

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Log in to Azure
      run: |
        az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
        az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./terraform

    - name: Debug Terraform Output (Receive Log Function)
      run: |
        echo "Terraform output for function_app_name_receive_log:"
        terraform output function_app_name_receive_log
      working-directory: ./terraform

    - name: Set FUNCTION_APP_NAME_RECEIVE_LOG
      run: |
        FUNCTION_APP_NAME_RECEIVE_LOG=$(terraform output -raw function_app_name_receive_log | tr -d '\r\n')
        FUNCTION_APP_NAME_RECEIVE_LOG=$(echo $FUNCTION_APP_NAME_RECEIVE_LOG | grep -o '^[^:]*')
        echo "FUNCTION_APP_NAME_RECEIVE_LOG=$FUNCTION_APP_NAME_RECEIVE_LOG" >> $GITHUB_ENV
      working-directory: ./terraform
    
    - name: Debug Terraform Output (Retrieve Log Function)
      run: |
        echo "Terraform output for function_app_name_retrieve_log:"
        terraform output function_app_name_retrieve_log
      working-directory: ./terraform
    
    - name: Set FUNCTION_APP_NAME_RETRIEVE_LOG
      run: |
        FUNCTION_APP_NAME_RETRIEVE_LOG=$(terraform output -raw function_app_name_retrieve_log | tr -d '\r\n')
        FUNCTION_APP_NAME_RETRIEVE_LOG=$(echo $FUNCTION_APP_NAME_RETRIEVE_LOG | grep -o '^[^:]*')
        echo "FUNCTION_APP_NAME_RETRIEVE_LOG=$FUNCTION_APP_NAME_RETRIEVE_LOG" >> $GITHUB_ENV
      working-directory: ./terraform
    
    - name: Get Publish Profile for Receive Log Function
      run: |
        echo "Getting publish profile for function app: ${{ env.FUNCTION_APP_NAME_RECEIVE_LOG }}"
        az webapp deployment list-publishing-profiles --name ${{ env.FUNCTION_APP_NAME_RECEIVE_LOG }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --output tsv > publishProfileReceiveLog.txt
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        FUNCTION_APP_NAME_RECEIVE_LOG: ${{ env.FUNCTION_APP_NAME_RECEIVE_LOG }}
    
    - name: Get Publish Profile for Retrieve Log Function
      run: |
        echo "Getting publish profile for function app: ${{ env.FUNCTION_APP_NAME_RETRIEVE_LOG }}"
        az webapp deployment list-publishing-profiles --name ${{ env.FUNCTION_APP_NAME_RETRIEVE_LOG }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --output tsv > publishProfileRetrieveLog.txt
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        FUNCTION_APP_NAME_RETRIEVE_LOG: ${{ env.FUNCTION_APP_NAME_RETRIEVE_LOG }}
    
    - name: Read Publish Profile for Receive Log Function
      run: |
        publish_profile=$(cat publishProfileReceiveLog.txt)
        echo "PUBLISH_PROFILE_RECEIVE_LOG=$publish_profile" >> $GITHUB_ENV

    - name: Read Publish Profile for Retrieve Log Function
      run: |
        publish_profile=$(cat publishProfileRetrieveLog.txt)
        echo "PUBLISH_PROFILE_RETRIEVE_LOG=$publish_profile" >> $GITHUB_ENV

    - name: Deploy Receive Log Function to Azure
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.FUNCTION_APP_NAME_RECEIVE_LOG }}
        package: "./ReceiveLogEntry"
        publish-profile: ${{ env.PUBLISH_PROFILE_RECEIVE_LOG }}

    - name: Deploy Retrieve Log Function to Azure
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.FUNCTION_APP_NAME_RETRIEVE_LOG }}
        package: "./RetrieveLogEntries"
        publish-profile: ${{ env.PUBLISH_PROFILE_RETRIEVE_LOG }}